### ISSUE TITLE
Example of Rendering Tiles

### ISSUE THREAD

**Issue by wyhinton** [glowcoil/ochre#1]
Hello, 

Thanks for the wonderful library. I was wondering if you knew of or had any thought of providing an example of visually rendering the tiles and spans on the gpu. I, and I'm sure others, could certainly use some help in understanding how to transform the tiles and spans into a visual output.

**Comment by micahrj** [comment]
There's actually an [svg example](https://github.com/glowcoil/ochre/blob/9daa6f000e61341cbd3617704ed708dfd7da9cbf/examples/svg.rs) which demonstrates how to upload and render the tiles and spans using OpenGL. 🙂

**Comment by wyhinton** [comment]
I see, great! Thanks. I'm going to take a crack at getting this working in [speedy2d](https://github.com/QuantumBadger/Speedy2D), hopefully I'll be able to pop back with a basic example soon.
