### ISSUE TITLE
Stroke Artifacts

### ISSUE THREAD

**Issue by AlexVestin** [glowcoil/ochre#2]
Hi! Awesome library

I've only briefly tried the renderer, but changing the resolution of the window I'm noticing some artifacts in the rendering.
For reference when using 800x600 it looks as expected:

![tiger2](https://user-images.githubusercontent.com/31164322/117313537-47e56a00-ae86-11eb-8959-2cd46448042c.png)

However doubling the size there seems to be some issues with continuation for strokes (1600x1200):
![tiger3](https://user-images.githubusercontent.com/31164322/117313636-5df32a80-ae86-11eb-84c6-4a7d890425b9.png)

The issue persists even when doubling the atlas size. 
I tried it out at https://github.com/AlexVestin/ochre since I got an error when building from the main one, something about an uninitialized X11 pointer  which seemed to be connected with outdated glutin, so there may be some use error going on from my end.

**Comment by micahrj** [comment]
The issue here is just that the window size is hard-coded in the example and I didn't bother to handle resizes at all. This isn't an artifact with Ochre's tile rendering, it's just that the example is scaling the tiles incorrectly in the vertex shader since the uniform for screen resolution isn't being updated when the screen is resized.

**Comment by AlexVestin** [comment]
I get that when setting the SCREEN_WIDTH / HEIGHT variables without resizing at runtime, and it looks like the correct resolution is uploaded in the uniform. What would need to be updated for it to render properly?

**Comment by AlexVestin** [comment]
Looks like the window manager does a resize if the window size is bigger than the display resolution, so you were right about it being a resize issue! Thanks
