### ISSUE TITLE
Rendering text

### ISSUE THREAD

**Issue by flowjo-isaach** [glowcoil/ochre#3]
I'm playing around with your example code and I'm not sure how to render text without converting characters into paths in SVG. I tried using a <text> element in the svg example with no luck. I just need to render basic letters and numbers, nothing fancy. Thank you.

**Comment by flowjo-isaach** [comment]
in retrospect, it would make more sense to use pathing for text in this library. I'll close this issue.

**Comment by micahrj** [comment]
Yes, Ochre is currently pretty bare-bones and doesn't provide anything text-specific. You could use a crate like [ttf-parser](https://crates.io/crates/ttf-parser) or [swash](https://crates.io/crates/swash) to extract outlines from fonts and then feed them to Ochre as paths.

**Comment by flowjo-isaach** [comment]
Great library by the way! Thank you for writing this.
